# Generated by Django 2.2.6 on 2019-11-02 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20191102_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Upvote',
        ),
    ]
